### Statistical functions in numpy

In [1]:
import numpy as np

In [2]:
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# mean() -> mean of all value inside the array or matrix
print(np.mean(array)) # output in -> float64
print(np.mean(array, axis=0)) # column wise
print(np.mean(array, axis=1)) # row wise

5.0
[4. 5. 6.]
[2. 5. 8.]


In [4]:
# std() -> standerd deviation 
print(np.std(array)) # output in -> float64
print(np.std(array, axis=0)) # column wise
print(np.std(array, axis=1)) # row wise

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [5]:
# meadian() -> calculates the meadian
print(np.median(array)) # output in -> float64
print(np.median(array, axis=0)) # column wise
print(np.median(array, axis=1)) # row wise

5.0
[4. 5. 6.]
[2. 5. 8.]


In [6]:
# var() -> variance of all values
print(np.var(array)) # output in -> float64
print(np.var(array, axis=0)) # column wise
print(np.var(array, axis=1)) # row wise

6.666666666666667
[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]


### Trignometric functions

In [7]:
 # sin() tan() cos()
np.sin(0)
np.tan(45)

np.float64(1.6197751905438615)

In [8]:
#dot product --> matrix1[m x n] * matrix2[p x q]  {n == p}  -->  output[m x q]
# np.dot(m1,m2)

arr1 = np.random.randint(1,10,(4,3))
arr2 = np.random.randint(1,10,(3,5))
print('arr1')
print(arr1)
print('arr2')
print(arr2)
#DOT PRODUCT
dotprod = np.dot(arr1,arr2) # [4 x 3] * [3 x 5] -> [4 x 5]
print(dotprod)


arr1
[[2 1 9]
 [3 1 8]
 [2 2 7]
 [1 3 7]]
arr2
[[7 7 3 8 1]
 [7 2 3 8 4]
 [9 6 8 4 5]]
[[102  70  81  60  51]
 [100  71  76  64  47]
 [ 91  60  68  60  45]
 [ 91  55  68  60  48]]


In [9]:
# log() -> log of all values of matrix
np.log(arr1)

array([[0.69314718, 0.        , 2.19722458],
       [1.09861229, 0.        , 2.07944154],
       [0.69314718, 0.69314718, 1.94591015],
       [0.        , 1.09861229, 1.94591015]])

In [10]:
#exp() -> exponential value inside matrix
np.exp(arr2)

array([[1.09663316e+03, 1.09663316e+03, 2.00855369e+01, 2.98095799e+03,
        2.71828183e+00],
       [1.09663316e+03, 7.38905610e+00, 2.00855369e+01, 2.98095799e+03,
        5.45981500e+01],
       [8.10308393e+03, 4.03428793e+02, 2.98095799e+03, 5.45981500e+01,
        1.48413159e+02]])

In [ ]:
# round() -> round the float value to nearest possible integer value in float
print(np.round(3.4)) #3.0
print(np.round(3.5)) #4.0
print(np.round(3.8)) #4.0
# ceil() 
print(np.ceil(3.4)) #4.0
print(np.ceil(3.5)) #4.0
print(np.ceil(3.8)) #4.0
# floor()
print(np.floor(3.4)) #3.0
print(np.floor(3.5)) #3.0
print(np.floor(3.8)) #3.0

3.0
4.0
4.0
4.0
4.0
4.0
3.0
3.0
3.0


In [19]:
# transpose() => m x n ---> n x m
# np.transpose(arr1)  or arr1.T
print("4 x 3 -->")
print(arr1)
print("3 x 4 -->")
print(np.transpose(arr1))
print("3 x 4 -->")
print(arr1.T)

4 x 3 -->
[[2 1 9]
 [3 1 8]
 [2 2 7]
 [1 3 7]]
3 x 4 -->
[[2 3 2 1]
 [1 1 2 3]
 [9 8 7 7]]
3 x 4 -->
[[2 3 2 1]
 [1 1 2 3]
 [9 8 7 7]]


In [20]:
# ravel() -> convert n-d array in 1-d array
print(arr1)
print(np.ravel(arr1))

[[2 1 9]
 [3 1 8]
 [2 2 7]
 [1 3 7]]
[2 1 9 3 1 8 2 2 7 1 3 7]


### Indexing and Slicing

In [ ]:
oneDArray = np.random.randint(1,10,9)
print(oneDArray)
# target 6th element  array[target-1]
print(oneDArray[5])

[9 4 3 6 4 7 4 4 2]
7


In [ ]:
# 2-D array -> [row,column]
print(arr1) # target 2nd row and 3rd column  -> 8
print(arr1[1,2])

[[2 1 9]
 [3 1 8]
 [2 2 7]
 [1 3 7]]
8


In [36]:
# 3-D array -> [z-axis , x-asix , y-axis]
ThreeDArray = np.arange(1,9).reshape(2,2,2)
ThreeDArray

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
# taeget 7 
ThreeDArray[1,1,0]

np.int64(7)

In [41]:
# slicing
# 1-d -> [:]
# 2-d -> [row1:rown,col1:coln]
print(arr1) # taeget middle two rows
print(arr1[1:3])
#target midlle of two elements 1 ,2
print(arr1[1:3,1:2])

[[2 1 9]
 [3 1 8]
 [2 2 7]
 [1 3 7]]
[[3 1 8]
 [2 2 7]]
[[1]
 [2]]


In [43]:
# Iteration 
# 1-d 
print(oneDArray)

[9 4 3 6 4 7 4 4 2]


In [44]:
for i in oneDArray:
    print(i)

9
4
3
6
4
7
4
4
2


In [45]:
for i in oneDArray:
    print(i>5)

True
False
False
True
False
True
False
False
False


In [47]:
print(arr1)
for i in arr1:
    print(i)

[[2 1 9]
 [3 1 8]
 [2 2 7]
 [1 3 7]]
[2 1 9]
[3 1 8]
[2 2 7]
[1 3 7]


In [48]:
print(ThreeDArray)
for i in ThreeDArray:
    print(i)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [49]:
# nditer() -> iteration over evry value in n-d array
for i in np.nditer(ThreeDArray):
    print(i)

1
2
3
4
5
6
7
8


In [50]:
#1D array -> value by value on iteration
#2D array -> row by row on iteration
#3D array -> 2d array by 2d array

In [ ]:
# Stacking and spliting 
