In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 11.9 MB/s eta 0:00:01
   -------------------------- ------------- 8.1/12.3 MB 37.1 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 28.5 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 26.3 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 17.4 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
#1-D array / vector
numpy_array = np.array([1,2,3,4,5])
numpy_array

array([1, 2, 3, 4, 5])

In [4]:
type(numpy_array)

numpy.ndarray

In [5]:
#2-D array / Matrix
TwoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
TwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(TwoDArray.ndim) 
print(TwoDArray.shape)
type(TwoDArray)


2
(3, 3)


numpy.ndarray

In [7]:
#3-D array / Tensor
ThreeDArray = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(ThreeDArray.ndim)
print(ThreeDArray.size)
ThreeDArray

3
12


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

* ndim -> tells the dimension of array
* shape -> tells number of rows and columns 
* size -> toatl number of elements
* itemsize -> size of a uniquie elements inside our array in bytes

In [8]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).itemsize # 8

8

In [9]:
np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int32).itemsize #4bytes each

4

#### we also specifie the size of data in array
#### with dtype -> helps for deciding about size of the data we are going to store inside our array 
* default is int64

In [10]:
array16bits = np.array([1,2,3,4,5], dtype=np.int16) # int8, int16, int32, int64, float16, float32, float64, float96, float128
print(type(array16bits)) # 8bits = 1byte
print(array16bits.dtype)
array16bits

<class 'numpy.ndarray'>
int16


array([1, 2, 3, 4, 5], dtype=int16)

### arange
#### helps in providing the values over a certain range

In [11]:
empty_list = []
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [12]:
np.arange(16) # 0 - 15(n-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
np.arange(0,16,2) #(start,end,jump)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### reshape

In [15]:
arange_data = np.arange(1,17)

In [16]:
arange_data.reshape(4,4) # 4x4 = 16 || n x m = total number of elements

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
np.arange(1,10).reshape(3,3) # (row,column)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# 3-d with reshape
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
#flatten array 2-d -> 1-d array
np.array([[1,2],[3,1]]).reshape(4)


array([1, 2, 3, 1])

In [20]:
#auto calculate one dimension
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,-1))  # 2 rows fix , auto fill columns

[[1 2 3]
 [4 5 6]]


### ones -> used in nueral networks to assign the weights 

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### random -> used in generating random values from 0 to 1

In [25]:
np.random.random(3)

array([0.48106497, 0.40331562, 0.34084055])

In [26]:
np.random.random((3,3))

array([[0.33708235, 0.17628457, 0.20259326],
       [0.72898858, 0.79472327, 0.67117211],
       [0.53576952, 0.14272574, 0.02264538]])

In [27]:
np.random.rand(3,3)  #rand() → Random Floats (0 to 1)

array([[0.01947818, 0.15721056, 0.25637979],
       [0.15176537, 0.6315655 , 0.01315792],
       [0.19035035, 0.55210718, 0.44858193]])

In [28]:
#suffle
a = np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[3 2 4 5 1]


In [29]:
#random choice
a = [10,20,30,40]
np.random.choice(a)

np.int64(10)

In [30]:
np.random.randint(1,10,5) # np.random.randint(low, high, size)

array([1, 9, 7, 8, 2], dtype=int32)

In [31]:
np.random.randint(1,100,(3,3)) # random matrix

array([[41, 21, 36],
       [36, 16, 41],
       [66, 32, 14]], dtype=int32)

In [32]:
#randn() → Normal Distribution
np.random.randn(5) #Values follow: mean = 0, standard deviation = 1

array([-0.64713537,  0.51271996, -0.96380081, -0.130404  , -1.33925386])

In [33]:
np.random.seed(42)
print(np.random.randint(1,10,5))

[7 4 8 5 7]


seed() sets the starting point for a pseudo-random number generator (PRNG).

Computers use mathematical formulas to generate numbers that only appear random.
Same seed → same sequence of random numbers.
Different seed → different sequence.

Example:

np.random.seed(42)

42 is just a popular programmer choice from The Hitchhiker's Guide to the Galaxy and has no special mathematical meaning.

In [34]:
#modern way
rng = np.random.default_rng()

rng.random((3,3))

array([[0.05371938, 0.82265235, 0.44943614],
       [0.18407484, 0.05553176, 0.17436817],
       [0.2794578 , 0.15248524, 0.38046599]])

In [35]:
rng = np.random.default_rng(43)
rng.random((3,3))

array([[0.65229926, 0.04377532, 0.02002959],
       [0.83921258, 0.58714305, 0.22470523],
       [0.75179227, 0.2636922 , 0.41997791]])

Important Difference in Functions

Old:
* np.random.randint()
* np.random.rand()
* np.random.randn()

Modern:
* rng.integers()
* rng.random()
* rng.normal()

identity() -> create matrix as an indentity matrix [square matrix -> row=column]

In [36]:
#Identity()
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

linspace() -> it makes sure that every value with the given range is going to have similar distance from each other

In [37]:
np.linspace(-10,10,10) # start,end,elements

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])