In [2]:
pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
#1-D array / vector
numpy_array = np.array([1,2,3,4,5])
numpy_array

array([1, 2, 3, 4, 5])

In [5]:
type(numpy_array)

numpy.ndarray

In [6]:
#2-D array / Matrix
TwoDArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
TwoDArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(TwoDArray.ndim) 
print(TwoDArray.shape)
type(TwoDArray)


2
(3, 3)


numpy.ndarray

In [61]:
#3-D array / Tensor
ThreeDArray = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(ThreeDArray.ndim)
print(ThreeDArray.size)
ThreeDArray

3
12


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

* ndim -> tells the dimension of array
* shape -> tells number of rows and columns 
* size -> toatl number of elements
* itemsize -> size of a uniquie elements inside our array in bytes

In [ ]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).itemsize # 8

8

In [ ]:
np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int32).itemsize #4bytes each

4

#### we also specifie the size of data in array
#### with dtype -> helps for deciding about size of the data we are going to store inside our array 
* default is int64

In [9]:
array16bits = np.array([1,2,3,4,5], dtype=np.int16) # int8, int16, int32, int64, float16, float32, float64, float96, float128
print(type(array16bits)) # 8bits = 1byte
print(array16bits.dtype)
array16bits

<class 'numpy.ndarray'>
int16


array([1, 2, 3, 4, 5], dtype=int16)

### arange
#### helps in providing the values over a certain range

In [10]:
empty_list = []
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [11]:
np.arange(16) # 0 - 15(n-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.arange(0,16,2) #(start,end,jump)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### reshape

In [14]:
arange_data = np.arange(1,17)

In [ ]:
arange_data.reshape(4,4) # 4x4 = 16 || n x m = total number of elements

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np.arange(1,10).reshape(3,3) # (row,column)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# 3-d with reshape
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
#flatten array 2-d -> 1-d array
np.array([[1,2],[3,1]]).reshape(4)


array([1, 2, 3, 1])

In [ ]:
#auto calculate one dimension
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,-1))  # 2 rows fix , auto fill columns

[[1 2 3]
 [4 5 6]]


### ones -> used in nueral networks to assign the weights 

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### random -> used in generating random values from 0 to 1

In [32]:
np.random.random(3)

array([0.21497165, 0.5846038 , 0.76234726])

In [36]:
np.random.random((3,3))

array([[0.81889465, 0.61206615, 0.77716308],
       [0.99482565, 0.08880509, 0.82330474],
       [0.07378589, 0.67355446, 0.57561684]])

In [40]:
np.random.rand(3,3)  #rand() → Random Floats (0 to 1)

array([[0.30995268, 0.63383547, 0.85100644],
       [0.94451956, 0.66037458, 0.27127476],
       [0.88447975, 0.86883124, 0.31130764]])

In [41]:
#suffle
a = np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[2 5 4 3 1]


In [42]:
#random choice
a = [10,20,30,40]
np.random.choice(a)

np.int64(20)

In [43]:
np.random.randint(1,10,5) # np.random.randint(low, high, size)

array([8, 8, 9, 7, 9])

In [48]:
np.random.randint(1,100,(3,3)) # random matrix

array([[83, 87, 75],
       [75, 88, 24],
       [ 3, 22, 53]])

In [ ]:
#randn() → Normal Distribution
np.random.randn(5) #Values follow: mean = 0, standard deviation = 1

array([ 0.76845925,  0.89870336, -1.30599294,  0.24383904, -0.10444636])

In [47]:
np.random.seed(42)
print(np.random.randint(1,10,5))

[7 4 8 5 7]


seed() sets the starting point for a pseudo-random number generator (PRNG).

Computers use mathematical formulas to generate numbers that only appear random.
Same seed → same sequence of random numbers.
Different seed → different sequence.

Example:

np.random.seed(42)

42 is just a popular programmer choice from The Hitchhiker's Guide to the Galaxy and has no special mathematical meaning.

In [ ]:
#modern way
rng = np.random.default_rng()

rng.random((3,3))

array([[0.8175139 , 0.09828397, 0.04938229],
       [0.27412529, 0.0443107 , 0.84801744],
       [0.61795997, 0.79830061, 0.30821548]])

In [53]:
rng = np.random.default_rng(43)
rng.random((3,3))

array([[0.65229926, 0.04377532, 0.02002959],
       [0.83921258, 0.58714305, 0.22470523],
       [0.75179227, 0.2636922 , 0.41997791]])

Important Difference in Functions

Old:
* np.random.randint()
* np.random.rand()
* np.random.randn()

Modern:
* rng.integers()
* rng.random()
* rng.normal()

identity() -> create matrix as an indentity matrix [square matrix -> row=column]

In [56]:
#Identity()
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

linspace() -> it makes sure that every value with the given range is going to have similar distance from each other

In [57]:
np.linspace(-10,10,10) # start,end,elements

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])