### Statistical functions in numpy

In [1]:
import numpy as np

In [3]:
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# mean() -> mean of all value inside the array or matrix
print(np.mean(array)) # output in -> float64
print(np.mean(array, axis=0)) # column wise
print(np.mean(array, axis=1)) # row wise

5.0
[4. 5. 6.]
[2. 5. 8.]


In [7]:
# std() -> standerd deviation 
print(np.std(array)) # output in -> float64
print(np.std(array, axis=0)) # column wise
print(np.std(array, axis=1)) # row wise

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [8]:
# meadian() -> calculates the meadian
print(np.median(array)) # output in -> float64
print(np.median(array, axis=0)) # column wise
print(np.median(array, axis=1)) # row wise

5.0
[4. 5. 6.]
[2. 5. 8.]


In [9]:
# var() -> variance of all values
print(np.var(array)) # output in -> float64
print(np.var(array, axis=0)) # column wise
print(np.var(array, axis=1)) # row wise

6.666666666666667
[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]


### Trignometric functions

In [ ]:
 # sin() tan() cos()
np.sin(0)
np.tan(45)

In [ ]:
#dot product --> matrix1[m x n] * matrix2[p x q]  {n == p}  -->  output[m x q]
# np.dot(m1,m2)

arr1 = np.random.randint(1,10,(4,3))
arr2 = np.random.randint(1,10,(3,5))
print('arr1')
print(arr1)
print('arr2')
print(arr2)
#DOT PRODUCT
dotprod = np.dot(arr1,arr2) # [4 x 3] * [3 x 5] -> [4 x 5]
print(dotprod)


arr1
[[7 5 5]
 [2 5 7]
 [6 2 8]
 [4 2 5]]
arr2
[[3 9 9 3 4]
 [9 1 1 3 8]
 [7 9 8 8 2]]
[[101 113 108  76  78]
 [100  86  79  77  62]
 [ 92 128 120  88  56]
 [ 65  83  78  58  42]]
