astype() -> it hepls in figuring out the data type of the column in dataset in pandas and it will be used in numpy as well for getting the data type changed of our in overall array

In [13]:
import numpy as np

In [14]:
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
array.astype('float64')


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
array.dtype

dtype('int64')

In [17]:
array = array.astype('float64')

In [18]:
array.dtype

dtype('float64')

### Mathematical operations 

In [24]:
# Scaler Operation -> a scaler value operation will be done with the array or a numeric value ( 1,4 ....)
array = np.random.rand(3,3)*100
array

array([[70.72390165, 28.06291669, 36.2505006 ],
       [95.39224264, 53.02736819, 53.98060404],
       [78.90104907, 90.49641334, 28.81680512]])

In [25]:
array = np.round(array)
array

array([[71., 28., 36.],
       [95., 53., 54.],
       [79., 90., 29.]])

In [26]:
array = array.astype('int32')
array

array([[71, 28, 36],
       [95, 53, 54],
       [79, 90, 29]], dtype=int32)

In [31]:
np.round(np.random.rand(3,3) * 100).astype('int32') # in one line 

array([[19, 64, 45],
       [63, 13, 63],
       [45, 73, 73]], dtype=int32)

In [ ]:
# Scaler operations with out matrix or array
print(array)
array+2  # add, sub, mul, divide, floor, modulo 

[[79 74 71]
 [28 99 90]
 [63 99  5]]


array([[ 81,  76,  73],
       [ 30, 101,  92],
       [ 65, 101,   7]], dtype=int32)

In [33]:
# relational operations
print(array)
array>60

[[79 74 71]
 [28 99 90]
 [63 99  5]]


array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [ ]:
# Vector operations on two given matrix 
arr1 = np.arange(1,17).reshape(4,4)
arr2 = np.arange(17,33).reshape(4,4)

print('arr1')
print(arr1)
print('arr2')
print(arr2)
print('arr1 + arr2')  # ->  + - * / 
print(arr1 + arr2)

arr1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr2
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
arr1 + arr2
[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]


### Important functions

In [39]:
# max() -> max value from that matric , array
np.max(arr1)

np.int64(16)

In [40]:
# axis --> help in getting the max or min value from specific row or column
# axis=0 column wise operation
# axis=1 row wise operation
array

array([[79, 74, 71],
       [28, 99, 90],
       [63, 99,  5]], dtype=int32)

In [ ]:
np.max(array,axis=0) # max value of each column

array([79, 99, 90], dtype=int32)

In [42]:
np.max(array,axis=1) # max value from each row 

array([79, 99, 99], dtype=int32)

In [43]:
print(np.min(array,axis=0)) # min value of each column
print(np.min(array,axis=1)) # min value of each row

[28 74  5]
[71 28  5]


In [44]:
# sum() -> calculates the total sum
array

array([[79, 74, 71],
       [28, 99, 90],
       [63, 99,  5]], dtype=int32)

In [47]:
print(np.sum(array)) # TOTAL SUM
print(np.sum(array,axis=0)) # TOTAL SUM COLUMN WISE
print(np.sum(array,axis=1)) # TOTAL SUM ROW WISE

608
[170 272 166]
[224 217 167]


In [48]:
# prod() -> product of all values  
print(np.prod(array)) # TOTAL PRODUCT
print(np.prod(array,axis=0)) # TOTAL PRODUCT COLUMN WISE
print(np.prod(array,axis=1)) # TOTAL PRODUCT ROW WISE

3229227509230800
[139356 725274  31950]
[415066 249480  31185]
