Task 2: Important Mathematical Operations

Given two arrays:

A = np.array([10, 20, 30, 40])

B = np.array([1, 2, 3, 4])

Perform and print results for:

1. Addition (A + B)

2. Subtraction (A - B)

3. Multiplication ( A ^ * B)

4. Division (A / B)

5. Power (A ^ 2)

In [1]:
import numpy as np

In [2]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

In [ ]:
print("A + B")
ArraySum1 = A + B
print(ArraySum1)

A + B
[11 22 33 44]


In [10]:
print("A + B")
ArraySum2 = np.add(A,B)
print(ArraySum2)

A + B
[11 22 33 44]


In [16]:
print("A - B")
ArraySubtracted = np.subtract(A,B)
print(ArraySubtracted)

A - B
[ 9 18 27 36]


In [17]:
print("A * B")
ArrayProducts = A * B
print(ArrayProducts)

A * B
[ 10  40  90 160]


In [14]:
print("A / B")
ArrayDivision = A + B
print(ArrayDivision)

A / B
[11 22 33 44]


In [15]:
print("A ** B")
ArrayPower = A ** B
print(ArrayPower)

A ** B
[     10     400   27000 2560000]
